language: java
jdk:
  - openjdk8
env:
  - MAVEN_VERSION=3.2.5
  - MAVEN_VERSION=3.3.9
install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"


cache:
    directories:
    - $HOME/.m2


notifications:
  email: akshayatp16@gmail.com
